# This workflow labels PRs for which automerge is enabled with a label so that we can easily spot them in the PR overview UI.

name: Label auto-merge PRs

on:
  pull_request_target:
    types: [ auto_merge_enabled, auto_merge_disabled ]
jobs:
  add_remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: ubuntudroid/automerge-labeler@v1
        with:
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          label: 'auto-merge' # optional